// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI1ojciZUvHPgPHfA3wTD0BLHmgU4Qo_I',
    appId: '1:923289747639:android:7e53b355b1c3918b054d32',
    messagingSenderId: '923289747639',
    projectId: 'newsimpactpro',
    storageBucket: 'newsimpactpro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg7vfXpIPILQzbFd9tnZJhVduuzIMNiSM',
    appId: '1:923289747639:ios:9452087e2ffa1988054d32',
    messagingSenderId: '923289747639',
    projectId: 'newsimpactpro',
    storageBucket: 'newsimpactpro.firebasestorage.app',
    androidClientId: '923289747639-if80a43rs0i5c8o1mpntuddss23ef79t.apps.googleusercontent.com',
    iosClientId: '923289747639-h71i8b2icbi73n40fboft8r4ud9t75od.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsimpactpro',
  );
}
